### ISSUE TITLE
link /etc/dhcp3 to make vCloud Guest Customization work

### ISSUE THREAD

**Issue by StefanScherer** [frapposelli/packer-templates#2]
Hi @frapposelli,

I have read your latest [article](http://gosddc.com/articles/dock-your-container-on-vmware-with-vagrant-and-docker/) of using Docker in vCenter and also vCloud. I stuck with Ubuntu 14.04 in our vCloud some time ago. But your article was interesting enough for me to look deeper what's wrong with the Ubuntu 14.04 boxes.

I tried my ubuntu1404 box, based on the box-cutter/ubuntu-vm Repo, but after powering on, the SSH connection does not work.
So I tried your gosddc/trusty64 box, but I run into the same problem. No SSH and so no provisioning etc.

I had to log into these two boxes with vCloud Director and found out that the network cards had problems. The `/etc/hostname` already has the correct name, as well as the `/etc/hosts` table is already updated. But no network connection. After rebooting the guest, SSH connection works.

After some googling, I found this [vmware community article](https://communities.vmware.com/message/2397050).

So I came up with a fix for my ubuntu1404 boxes with this  [commit](https://github.com/StefanScherer/ubuntu-vm/commit/7591c1f49b3aa1e31000d80635dd289757d445a1) in `my` branch. I just followed the tip that a symbolic link `/etc/dhcp3` should exist and point to `/etc/dhcp`.

And yes, my ubuntu1404 box is built correctly and was testable with my basebox-slave serverspec tests.

Seems to do the trick.

So it might be helpful for others that the gosddc/trusty\* boxes should also have this patch.

Do you have another patch/update for the vCloud that fixes it inside the Guest Customization scripts?

I don't know our exact vCloud Director version.

**Comment by StefanScherer** [comment]
I have a running [Dock your Container example](https://github.com/StefanScherer/vcloud-scenarios/tree/master/docker-test) running in our vCloud. But I had another issue with missing entries in `/etc/resolv.conf`. I then added a shell provision script that helps me to make DNS lookup work.
Any hints what's wrong?

**Comment by frapposelli** [comment]
I will look into that shortly, the `/etc/resolv.conf` problem is an old one, I think it's due to an upstream bug in vCD.
