### ISSUE TITLE
Boxes are no longer available on vagrant-cloud

### ISSUE THREAD

**Issue by vladistan** [frapposelli/packer-templates#4]
Looks like Vagrant guys have revamped the whole side.  There is no more Vagrant cloud,  everything has moved to Atlas.   Unfortunately your boxes did not migrate correctly :-(

**Comment by frapposelli** [comment]
Yes, all of them are gone except for `gosddc/precise32`, I'm working on reinstating them but it's going to take some time...

**Comment by vladistan** [comment]
Cool.  I've building my own over the weekend using 'Atlas'  build facility.   Can share with you if you want a head start.
